name: pecs_new_arch
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+6

environment:
  sdk: ^3.6.0
dependencies:
  flutter:
    sdk: flutter
  auto_route: ^10.0.1
  flutter_svg: ^2.0.10+1
  mask_text_input_formatter: ^2.8.0
  file_picker: ^10.0.0
  image_picker: ^1.1.2
  camera: ^0.11.1
  go_router: ^14.8.1
  easy_localization: ^3.0.7+1
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  shared_preferences: ^2.5.1
  freezed_annotation: ^2.4.4
  get_it: ^8.0.3
  flutter_secure_storage: ^10.0.0-beta.4
  google_fonts: ^6.2.1
  encrypt: ^5.0.3
  tuple: ^2.0.2
  crypto: ^3.0.6
  device_preview: ^1.2.0
  gal: ^2.3.1
  # * -- [NETWORK]
  dio: ^5.8.0+1
  dio_cache_interceptor: ^4.0.3
  pretty_dio_logger: ^1.4.0
  http: ^1.3.0
  async: ^2.11.0
  flutter_bloc: ^9.0.0
  bloc: ^9.0.0
  # * -- [NAVIGATION]
  awesome_extensions: ^2.0.15
  chucker_flutter: 1.8.3  
  flutter_screenutil: ^5.9.3
  path_provider: ^2.1.1
  loader_overlay: ^5.0.0
  video_compress: ^3.1.3
  html: ^0.15.5
  flutter_local_notifications: ^19.0.0
  open_filex: ^4.5.0
  # lutter_screen_recording: ^2.0.19
  path: ^1.9.0
  infinite_scroll_pagination: ^5.0.0
  permission_handler: ^11.4.0
  readmore: ^3.0.0
  shimmer: ^3.0.0
  hive_flutter: ^1.1.0
  flutter_colorpicker: ^1.1.0
  super_drag_and_drop: ^0.8.24
  just_audio: ^0.9.36
  dropdown_search: ^5.0.6
  flutter_side_menu: ^0.5.41
  badges: ^3.1.2
  sidebarx: ^0.17.1
flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/svg/
    - assets/translations/
    - assets/jpg/
    - assets/icons/svg/
    - assets/images/


  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat.ttf

flutter_gen:
  output: lib/gen/
  line_length: 80
  integrations:
    flutter_svg: true

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  freezed: ^2.5.2
  build_runner: ^2.4.9
  json_serializable: ^6.8.0
  auto_route_generator: ^10.0.1

  




